version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: production
    env_file:
      - path: ./.env
        required: true

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

  nginx:
    build:
      context: ./nginx  # Chemin vers le Dockerfile de Nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt  # Monté pour les certificats SSL
    depends_on:
      - grafana  # Nginx dépend de Grafana

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait; done;'"
  
volumes:
  grafana-storage:

# // attention mon container docker grafana et prometheus doivent être démarer manuellement avec 
# # Démarrer Grafana
# docker run -d -p 3000:3000 --name grafana grafana/grafana:latest

# # Démarrer Prometheus
# docker run -d -p 9090:9090 --name prometheus prom/prometheus:latest

# et docker ps pour vérifier que les containers sont bien démarrer

# Une fois les conteneurs démarrés, accédez aux services via les URLs suivantes :

# Grafana : http://35.180.32.62:3000
# Prometheus : http://35.180.32.62:9090


# docker start $(docker ps -a -q) pour démarrer tous les containers ou redemarer les containers