// app/prisma/seed.ts
import prisma from "../prisma";

import { Curencies } from "@prisma/client";

export async function seed() {
  await prisma.curencies.deleteMany();

  const currencies: Curencies[] = [
    { id: 0, name: "Albania Lek", devise: "Lek" },
    { id: 0, name: "Afghanistan Afghani", devise: "؋" },
    { id: 0, name: "Argentina Peso", devise: "$" },
    { id: 0, name: "Aruba Guilder", devise: "ƒ" },
    { id: 0, name: "Australia Dollar", devise: "$" },
    { id: 0, name: "Azerbaijan Manat", devise: "₼" },
    { id: 0, name: "Bahamas Dollar", devise: "$" },
    { id: 0, name: "Barbados Dollar", devise: "$" },
    { id: 0, name: "Belarus Ruble", devise: "Br" },
    { id: 0, name: "Belize Dollar", devise: "BZ$" },
    { id: 0, name: "Bermuda Dollar", devise: "$" },
    { id: 0, name: "Bolivia Bolíviano", devise: "$b" },
    { id: 0, name: "Bosnia and Herzegovina Convertible Mark", devise: "KM" },
    { id: 0, name: "Botswana Pula", devise: "P" },
    { id: 0, name: "Bulgaria Lev", devise: "лв" },
    { id: 0, name: "Brazil Real", devise: "R$" },
    { id: 0, name: "Brunei Darussalam Dollar", devise: "$" },
    { id: 0, name: "Cambodia Riel", devise: "៛" },
    { id: 0, name: "Canada Dollar", devise: "$" },
    { id: 0, name: "Cayman Islands Dollar", devise: "$" },
    { id: 0, name: "Chile Peso", devise: "$" },
    { id: 0, name: "China Yuan Renminbi", devise: "¥" },
    { id: 0, name: "Colombia Peso", devise: "$" },
    { id: 0, name: "Costa Rica Colon", devise: "₡" },
    { id: 0, name: "Croatia Kuna", devise: "kn" },
    { id: 0, name: "Cuba Peso", devise: "₱" },
    { id: 0, name: "Czech Republic Koruna", devise: "Kč" },
    { id: 0, name: "Denmark Krone", devise: "kr" },
    { id: 0, name: "Dominican Republic Peso", devise: "RD$" },
    { id: 0, name: "East Caribbean Dollar", devise: "$" },
    { id: 0, name: "Egypt Pound", devise: "£" },
    { id: 0, name: "El Salvador Colon", devise: "$" },
    { id: 0, name: "Euro Member Countries", devise: "€" },
    { id: 0, name: "Falkland Islands (Malvinas) Pound", devise: "£" },
    { id: 0, name: "Fiji Dollar", devise: "$" },
    { id: 0, name: "Ghana Cedi", devise: "¢" },
    { id: 0, name: "Gibraltar Pound", devise: "£" },
    { id: 0, name: "Guatemala Quetzal", devise: "Q" },
    { id: 0, name: "Guernsey Pound", devise: "£" },
    { id: 0, name: "Guyana Dollar", devise: "$" },
    { id: 0, name: "Honduras Lempira", devise: "L" },
    { id: 0, name: "Hong Kong Dollar", devise: "$" },
    { id: 0, name: "Hungary Forint", devise: "Ft" },
    { id: 0, name: "Iceland Krona", devise: "kr" },
    { id: 0, name: "India Rupee", devise: "" },
    { id: 0, name: "Indonesia Rupiah", devise: "Rp" },
    { id: 0, name: "Iran Rial", devise: "﷼" },
    { id: 0, name: "Isle of Man Pound", devise: "£" },
    { id: 0, name: "Israel Shekel", devise: "₪" },
    { id: 0, name: "Jamaica Dollar", devise: "J$" },
    { id: 0, name: "Japan Yen", devise: "¥" },
    { id: 0, name: "Jersey Pound", devise: "£" },
    { id: 0, name: "Kazakhstan Tenge", devise: "лв" },
    { id: 0, name: "Korea (North) Won", devise: "₩" },
    { id: 0, name: "Korea (South) Won", devise: "₩" },
    { id: 0, name: "Kyrgyzstan Som", devise: "лв" },
    { id: 0, name: "Laos Kip", devise: "₭" },
    { id: 0, name: "Lebanon Pound", devise: "£" },
    { id: 0, name: "Liberia Dollar", devise: "$" },
    { id: 0, name: "Macedonia Denar", devise: "ден" },
    { id: 0, name: "Malaysia Ringgit", devise: "RM" },
    { id: 0, name: "Mauritius Rupee", devise: "₨" },
    { id: 0, name: "Mexico Peso", devise: "$" },
    { id: 0, name: "Mongolia Tughrik", devise: "₮" },
    { id: 0, name: "Mozambique Metical", devise: "MT" },
    { id: 0, name: "Namibia Dollar", devise: "$" },
    { id: 0, name: "Nepal Rupee", devise: "₨" },
    { id: 0, name: "Netherlands Antilles Guilder", devise: "ƒ" },
    { id: 0, name: "New Zealand Dollar", devise: "$" },
    { id: 0, name: "Nicaragua Cordoba", devise: "C$" },
    { id: 0, name: "Nigeria Naira", devise: "₦" },
    { id: 0, name: "Norway Krone", devise: "kr" },
    { id: 0, name: "Oman Rial", devise: "﷼" },
    { id: 0, name: "Pakistan Rupee", devise: "₨" },
    { id: 0, name: "Panama Balboa", devise: "B/." },
    { id: 0, name: "Paraguay Guarani", devise: "Gs" },
    { id: 0, name: "Peru Sol", devise: "S/." },
    { id: 0, name: "Philippines Peso", devise: "₱" },
    { id: 0, name: "Poland Zloty", devise: "zł" },
    { id: 0, name: "Qatar Riyal", devise: "﷼" },
    { id: 0, name: "Romania Leu", devise: "lei" },
    { id: 0, name: "Russia Ruble", devise: "₽" },
    { id: 0, name: "Saint Helena Pound", devise: "£" },
    { id: 0, name: "Saudi Arabia Riyal", devise: "﷼" },
    { id: 0, name: "Serbia Dinar", devise: "Дин." },
    { id: 0, name: "Seychelles Rupee", devise: "₨" },
    { id: 0, name: "Singapore Dollar", devise: "$" },
    { id: 0, name: "Solomon Islands Dollar", devise: "$" },
    { id: 0, name: "Somalia Shilling", devise: "S" },
    { id: 0, name: "South Africa Rand", devise: "R" },
    { id: 0, name: "Sri Lanka Rupee", devise: "₨" },
    { id: 0, name: "Sweden Krona", devise: "kr" },
    { id: 0, name: "Switzerland Franc", devise: "CHF" },
    { id: 0, name: "Suriname Dollar", devise: "$" },
    { id: 0, name: "Syria Pound", devise: "£" },
    { id: 0, name: "Taiwan New Dollar", devise: "NT$" },
    { id: 0, name: "Thailand Baht", devise: "฿" },
    { id: 0, name: "Trinidad and Tobago Dollar", devise: "TT$" },
    { id: 0, name: "Turkey Lira", devise: "" },
    { id: 0, name: "Tuvalu Dollar", devise: "$" },
    { id: 0, name: "Ukraine Hryvnia", devise: "₴" },
    { id: 0, name: "United Kingdom Pound", devise: "£" },
    { id: 0, name: "United States Dollar", devise: "$" },
    { id: 0, name: "Uruguay Peso", devise: "$U" },
    { id: 0, name: "Uzbekistan Som", devise: "лв" },
    { id: 0, name: "Venezuela Bolívar", devise: "Bs" },
    { id: 0, name: "Viet Nam Dong", devise: "₫" },
    { id: 0, name: "Yemen Rial", devise: "﷼" },
    { id: 0, name: "Zimbabwe Dollar", devise: "Z$" },
  ].map((x, i) => {
    x.id = i + 1;
    return x;
  });

  const addCurency = async () =>
    await prisma.curencies.createMany({ data: currencies });

  addCurency();
}
