global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:3000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: "node_exporter"
    static_configs:
      - targets: ["15.236.190.151:9100"] 
