apiVersion: apps/v1
kind: Deployment
metadata:
  name: kakeibo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kakeibo-api
  template:
    metadata:
      labels:
        app: kakeibo-api
    spec:
      containers:
      - name: kakeibo-api
        image: bricesensei/kakeibo_api:latest
        ports:
        - containerPort: 8080
      env:
        - name: NODE_ENV
          value: production 
