apiVersion: apps/v1
kind: Deployment
metadata:
  name: kakeibo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kakeibo-api
  template:
    metadata:
      labels:
        app: kakeibo-api
    spec:
      imagePullSecrets:
        - name: myregistrykey
      containers:
      - name: kakeibo-api
        image: bricesensei/kakeibo_api:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"  # Réduit à 64 Mi
            cpu: "250m"     # Réduit à 250m (0.25 CPU)
          limits:
            memory: "128Mi" # Réduit à 128 Mi
            cpu: "250m"     # Réduit à 250m (0.25 CPU)
        env: 
          - name: NODE_ENV
            value: production
