# apiVersion: v1
# kind: Service
# metadata:
#   name: kakeibo-api-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: kakeibo-api
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080

# old test 
apiVersion: v1
kind: Service
metadata:
  name: kakeibo-api-service
spec:
  type: NodePort
  selector:
    app: kakeibo-api
  ports:
    - protocol: TCP
      port: 8080           # Port exposé dans le service
      targetPort: 8080     # Port cible dans les pods
      nodePort: 30008      # Port exposé sur chaque nœud
