---
- name: Install Minikube and kubectl
  hosts: kubectl_nodes
  become: true
  tasks:
    - name: Ensure necessary dependencies are installed
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
        state: present
        update_cache: yes

    - name: Install kubectl
      shell: |
        curl -Lo /usr/local/bin/kubectl https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
        chmod +x /usr/local/bin/kubectl

    - name: Install Minikube
      shell: |
        curl -Lo /usr/local/bin/minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x /usr/local/bin/minikube

    - name: Start Minikube
      shell: minikube start --driver=docker
