---
- name: Install kubectl
  hosts: kubectl_nodes
  become: true
  tasks:
    - name: Ensure necessary dependencies are installed
      apt:
        name:
          - curl
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Download the latest version of kubectl
      get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
        dest: /tmp/kubectl
        mode: '0755'
      vars:
        kubectl_version: "{{ lookup('url', 'https://dl.k8s.io/release/stable.txt') }}"

    - name: Move kubectl to /usr/local/bin
      command: mv /tmp/kubectl /usr/local/bin/kubectl

    - name: Verify kubectl installation
      command: kubectl version --client
      register: kubectl_version_output

    - name: Print kubectl version
      debug:
        msg: "{{ kubectl_version_output.stdout }}"
