interface UsersInterface {
    id: number;
    name: string;
    firstName: string;
    lastName: string;
    email: string;
    password: string;
    creationDate: Date;
    updateDate: Date;
    passwordUpdateDate: Date;
    lastLoginDate: Date;
    connectionAttempts: number;
    isActive: boolean;
    role: number;
    curencyId: number;
    curency: CurenciesInterface;
    tokens: TokensInterface[];
    fbTokens: FbTokensInterface[];
    alerts: AlertsInterface[];
    epargnes: EpargnesInterface[];
    frequancies: FrequenciesInterface[];
    subCategories: SubCategoriesInterface[];
    groups: UserGroupsInterface[];
};
