name: CD pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Check Docker version
        run: docker --version
      - name: Check Docker info
        run: docker info

      - name: Pull Docker image
        run: docker pull bricesensei/kakeibo_api:latest

      - name: Delete old Docker container
        run: |
          if [ $(docker ps -a -q -f name=kakeibo_api) ]; then
            docker rm -f kakeibo_api
          fi
      
      - name: Check if port 8080 is in use
        run: sudo lsof -i -P -n | grep LISTEN

      - name: Run new Docker container
        run: |
          docker run -d -p 8080:8080 --name kakeibo_api bricesensei/kakeibo_api:latest
  
      - name: Run Grafana
        run: |
          if [ $(docker ps -a -q -f name=grafana) ]; then
            docker rm -f grafana
          fi
          docker run -d -p 3000:3000 --name grafana \
          -v grafana-storage:/var/lib/grafana \
          grafana/grafana:latest

      - name: Prepare Prometheus config directory
        run: |
          mkdir -p ~/prometheus_config
                  
      - name: Copy Prometheus config from kakeibo_api
        run: |
          docker cp kakeibo_api:/app/prometheus/prometheus.yml ~/prometheus_config/prometheus.yml
            
      - name: Run Prometheus
        run: |
          if [ $(docker ps -a -q -f name=prometheus) ]; then
            docker rm -f prometheus
          fi
          docker run -d -p 9090:9090 --name prometheus \
          -v ~/prometheus_config/prometheus.yml:/etc/prometheus/prometheus.yml \
          prom/prometheus:latest
    
      - name: Run Nginx
        run: |
            sudo systemctl enable nginx
            sudo systemctl restart nginx

      - name: Start Node Exporter
        run: |
            sudo systemctl start node_exporter
          
      - name: stop minikube
        run: |
          minikube stop
      
      - name: start minikube
        run: |
          minikube start
      
      # - name: Create kubeconfig
      #   run: |
      #     mkdir -p $HOME/.kube
      #     echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
      #     cat $HOME/.kube/config

      - name: Create context
        run: |
          kubectl config set-context minikube --cluster=minikube --user=minikube
          
      - name: Use context
        run: | 
          kubectl config use-context minikube

      - name: verify status minikube
        run: |
          kubectl get all

      - name: Deploy to K8s
        if: success()
        run: |
          kubectl apply -f kubernetes/ --validate=false

      - name: Run integration tests
        run: |
          npm test

      - name: get log if failed
        if: failure()
        run: |
          kubectl get events
      
      - name: verify deployment
        run: |
          kubectl get all

      # - name: Set up kubeconfig
      #   run: |
      #     mkdir -p $HOME/.kube
      #     echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
      #     chmod 600 $HOME/.kube/config
      #     cat $HOME/.kube/config  # Optionnel : pour déboguer, supprimer ou commenter en production
      #   shell: bash
    
      # - name: Test kubectl
      #   run: |
      #     echo "Lister toutes les ressources Kubernetes :"
      #     kubectl get all -v=6  # Active le mode verbeux pour plus de détails
      #   shell: bash

      # - name: Verify Kubernetes manifests
      #   run: |
      #     echo "Vérification des manifestes Kubernetes :"
      #     ls -la kubernetes
      #     cat kubernetes/deployment.yml
      #     cat kubernetes/service.yml

      # - name: Apply Kubernetes manifests
      #   run: |
      #     echo "Application des manifestes Kubernetes avec mode verbeux :"
      #     kubectl apply -f kubernetes/deployment.yml -v=6
      #     kubectl apply -f kubernetes/service.yml -v=6
      #   shell: bash

      # - name: Set up kubeconfig
      #   run: |
      #     mkdir -p $HOME/.kube
      #     echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
      #     chmod 600 $HOME/.kube/config
      #     echo "Vérification du contexte actuel de kubectl :"
      #     kubectl config current-context  # Vérifie que le bon contexte est utilisé
      #   shell: bash

      
