name: CD pipeline

on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Pull Docker image
        run: docker pull bricesensei/kakeibo_api:latest

      - name: Delete old Docker container
        run: |
          if [ $(docker ps -a -q -f name=kakeibo_api) ]; then
            docker rm -f kakeibo_api
          fi

      - name: Run new Docker container
        run: |
          docker run -d -p 8080:8080 --name kakeibo_api bricesensei/kakeibo_api:latest

      - name: Delete existing Grafana container if it exists
        run: |
          if [ $(docker ps -a -q -f name=grafana) ]; then
            docker rm -f grafana
          fi

      - name: Run Grafana
        run: docker run -d -p 3000:3000 --name grafana grafana/grafana:latest

      - name: Delete existing Prometheus container if it exists
        run: |
          if [ $(docker ps -a -q -f name=prometheus) ]; then
            docker rm -f prometheus
          fi

      - name: Run Prometheus
        run: docker run -d -p 9090:9090 --name prometheus prom/prometheus:latest

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f deployment.yml
          kubectl apply -f service.yml
