name: CD pipeline
    
on:
  workflow_run:
    workflows: ["CI pipeline"]
    types:
      - completed
    
jobs:
    build: 
        runs-on: self-hosted

        steps: 
          - name: Pull Docker image
            run: sudo docker pull bricesensei/kakeibo_api:lastest
          - name: Delete old docker container
            run: sudo docker rm -f kakeibo_api || true
          - name: Run new docker container
            run: |
              sudo docker run -d -p 8080:8080 --name kakeibo_api bricesensei/kakeibo_api:lastest